### ISSUE TITLE
generated patches by repairSStuBs?

### ISSUE THREAD

**Issue by monperrus** [h4iku/repairSStuBs#1]
Hi,

Thanks for the cool repo.

Are the patches by repairSStuBs available somewhere?

Thanks,

--Martin

**Comment by h4iku** [comment]
Hi Martin,
Thank you, I'm glad to see you interested.

I uploaded the generated patches for the `sstubs.json` version of the dataset here:
https://www.mediafire.com/file/jd9byxt3qcxy7bu/repair_output.zip/file

However, there are a few things about these results:
1. Detecting lines are done using a heuristic. Ideally, I should've used a parser to not mess things up.
2. There might be some overlap between the train and test data since they both are collected from popular GitHub projects.
3. There are some duplicates in the dataset that I have not removed.
4. Some bugs have a wrong line number in the dataset that can only be found manually.
